/* auto-generated by NAPI-RS */
/* eslint-disable */
export declare class Assembly {
  constructor(outputPath: string)
  /** Appends one complete single-shard PDF; returns its page count. */
  appendShard(shardPath: string): number
  /** Total pages appended so far. */
  get pageCount(): number
  /** Writes the assembled document, with optional bookmarks. Consumed. */
  finalize(outline?: Array<OutlineEntry> | undefined | null): void
}

/**
 * One bookmark in the document outline (flat preorder list; `level` gives
 * nesting — a child is exactly one level deeper than its parent).
 */
export interface OutlineEntry {
  title: string
  /** 0-based absolute page index in the assembled document. */
  pageIndex: number
  level: number
}
