/* auto-generated by NAPI-RS */
/* eslint-disable */
export declare class Assembly {
  constructor(outputPath: string)
  /** Appends one complete single-shard PDF; returns its page count. */
  appendShard(shardPath: string): number
  /** Total pages appended so far. */
  get pageCount(): number
  /** Writes the assembled document. The assembly is consumed. */
  finalize(): void
}
