/* auto-generated by NAPI-RS */
/* eslint-disable */
export declare class Assembly {
  constructor(outputPath: string)
  /**
   * Appends one complete single-shard PDF; returns its page count.
   * Synchronous: blocks the event loop for the duration of the parse.
   */
  appendShard(shardPath: string): number
  /** Total pages appended so far. */
  get pageCount(): number
  /** Whether `finalize()` or `abort()` has already consumed this assembly. */
  get consumed(): boolean
  /**
   * Closes the partial output without finalizing it. Idempotent: calling
   * it on an already-consumed assembly is a no-op, so `finally` blocks can
   * call it unconditionally.
   */
  abort(): void
  /**
   * Writes the assembled document, with optional bookmarks. Consumed.
   * `level` may be omitted per entry (defaults to 0).
   */
  finalize(outline?: Array<OutlineEntry> | undefined | null): void
}

/**
 * Extract an inclusive, 1-based page range from `inputPath` into
 * `outputPath`, copying only objects the selected pages reach. Returns the
 * extracted page count. v1 drops link annotations, named destinations, and
 * outlines from the result — parity note: a qpdf page slice also loses
 * bookmarks, and keeps links only as silently-dangling targets.
 */
export declare function extractPages(inputPath: string, startPage: number, endPage: number, outputPath: string): number

/**
 * One bookmark in the document outline (flat preorder list; `level` gives
 * nesting — a child is exactly one level deeper than its parent).
 */
export interface OutlineEntry {
  title: string
  /** 0-based absolute page index in the assembled document. */
  pageIndex: number
  /** Nesting depth; defaults to 0 when omitted. */
  level?: number
}
