/* auto-generated by NAPI-RS */
/* eslint-disable */
export declare class Assembly {
  constructor(outputPath: string, options?: LoadOptions | undefined | null)
  /**
   * Appends one complete single-shard PDF; returns its page count.
   * Synchronous: blocks the event loop for the duration of the parse.
   * `SHARDPDF_INVALID_ARG` if an async call on this assembly is in flight.
   */
  appendShard(shardPath: string): number
  /**
   * Appends one complete single-shard PDF held in memory; returns its
   * page count. The buffer is parsed synchronously and not retained.
   * `SHARDPDF_INVALID_ARG` if an async call on this assembly is in flight.
   */
  appendShardBytes(bytes: Uint8Array): number
  /**
   * `appendShard` on the libuv threadpool. Resolves with the shard's page
   * count. The assembly is busy until the promise settles: any other call
   * in the meantime fails with `SHARDPDF_INVALID_ARG`.
   */
  appendShardAsync(shardPath: string): Promise<number>
  /**
   * `appendShardBytes` on the libuv threadpool. The bytes are copied
   * before the task is queued, so the caller may reuse the buffer as soon
   * as this returns. Same busy rule as `appendShardAsync`.
   */
  appendShardBytesAsync(bytes: Uint8Array): Promise<number>
  /**
   * Total pages appended so far. `SHARDPDF_INVALID_ARG` while an async
   * call is in flight.
   */
  get pageCount(): number
  /** Whether `finalize()` or `abort()` has already consumed this assembly. */
  get consumed(): boolean
  /** Whether an async call on this assembly is in flight. */
  get busy(): boolean
  /**
   * Closes the partial output without finalizing it. Idempotent: calling
   * it on an already-consumed assembly is a no-op, so `finally` blocks can
   * call it unconditionally. If an async call is in flight the writer is
   * closed as soon as that task settles; the task's own promise still
   * reports its result.
   */
  abort(): void
  /**
   * Writes the assembled document, with optional bookmarks. Consumed.
   * `level` may be omitted per entry (defaults to 0).
   * `SHARDPDF_INVALID_ARG` if an async call on this assembly is in flight.
   */
  finalize(outline?: Array<OutlineEntry> | undefined | null): void
  /**
   * `finalize` on the libuv threadpool. The assembly is consumed once the
   * promise settles, whether it resolved or rejected. Same busy rule as
   * `appendShardAsync`.
   */
  finalizeAsync(outline?: Array<OutlineEntry> | undefined | null): Promise<void>
}

export declare function buildInfo(): BuildInfo

/**
 * Build information for the loaded native module. Benchmarks record this
 * so a debug binary can never be mistaken for a release measurement.
 */
export interface BuildInfo {
  /** `"release"` or `"debug"` (Cargo profile the binding was compiled with). */
  profile: string
  /** Crate version from Cargo.toml. */
  version: string
}

/**
 * Extract an inclusive, 1-based page range from `inputPath` into
 * `outputPath`, copying only objects the selected pages reach. Returns the
 * extracted page count. v1 drops ALL annotations (links, widgets, and any
 * other /Annots entries), named destinations, and outlines from the result.
 * Parity note: a qpdf page slice also loses bookmarks, but keeps
 * annotations, with links to pages outside the range left dangling.
 */
export declare function extractPages(inputPath: string, startPage: number, endPage: number, outputPath: string, options?: LoadOptions | undefined | null): number

/**
 * Extract zero-based page indices from `input` (a path or PDF bytes) into
 * `outputPath`, in the order given. The source is parsed exactly once.
 * Returns the extracted page count. Same object-copy semantics as
 * `extractPages`: all annotations, named destinations, and outlines are
 * dropped. An empty array, a duplicate, a non-integer, a negative, or an
 * out-of-range index is `SHARDPDF_INVALID_ARG`.
 */
export declare function extractSelection(input: string | Uint8Array, pages: Array<number>, outputPath: string, options?: LoadOptions | undefined | null): number

/**
 * `extractSelection` on the libuv threadpool. Same arguments, semantics,
 * and error codes; byte input is copied before the task is queued. Resolves
 * with the extracted page count.
 */
export declare function extractSelectionAsync(input: string | Uint8Array, pages: Array<number>, outputPath: string, options?: LoadOptions | undefined | null): Promise<number>

/**
 * Optional resource limits for parsing shards.
 *
 * `maxDecompressedBytes` bounds how far any one compressed stream may
 * inflate while a shard is parsed. Shards you rendered yourself do not
 * need it; set it whenever a path or upload from outside your process can
 * reach `appendShard` or `extractPages`, because a 250 KB file can
 * otherwise allocate gigabytes before the core sees a single page. An
 * over-budget object stream is skipped by the parser, so the shard then
 * fails as `SHARDPDF_MALFORMED` (typically "shard has no pages") or, if
 * only a content stream was oversized, `SHARDPDF_PDF_PARSE`.
 */
export interface LoadOptions {
  maxDecompressedBytes?: number
}

/**
 * One bookmark in the document outline (flat preorder list; `level` gives
 * nesting — a child is exactly one level deeper than its parent).
 */
export interface OutlineEntry {
  title: string
  /** 0-based absolute page index in the assembled document. */
  pageIndex: number
  /** Nesting depth; defaults to 0 when omitted. */
  level?: number
}

/**
 * Parse `input` (a path or PDF bytes) and return its page count. Nothing
 * is written. Synchronous: the whole document is parsed on the JS thread.
 */
export declare function pageCount(input: string | Uint8Array, options?: LoadOptions | undefined | null): number

/**
 * Parse `input` (a path or a `Uint8Array`, which is copied) on the libuv
 * threadpool and resolve with its page count. Rejections carry the same
 * `SHARDPDF_*` codes as `pageCount`, including `SHARDPDF_PANIC`.
 */
export declare function pageCountAsync(input: string | Uint8Array, options?: LoadOptions | undefined | null): Promise<number>
