/* auto-generated by NAPI-RS */
/* eslint-disable */
export declare class Assembly {
  constructor(outputPath: string)
  /** Appends one complete single-shard PDF; returns its page count. */
  appendShard(shardPath: string): number
  /** Total pages appended so far. */
  get pageCount(): number
  /** Closes the partial output without finalizing it. Consumed. */
  abort(): void
  /** Writes the assembled document, with optional bookmarks. Consumed. */
  finalize(outline?: Array<OutlineEntry> | undefined | null): void
}

/**
 * Extract an inclusive, 1-based page range from `inputPath` into
 * `outputPath`, copying only objects the selected pages reach. Returns the
 * extracted page count. v1 drops link annotations, named destinations, and
 * outlines from the result — parity note: a qpdf page slice also loses
 * bookmarks, and keeps links only as silently-dangling targets.
 */
export declare function extractPages(inputPath: string, startPage: number, endPage: number, outputPath: string): number

/**
 * One bookmark in the document outline (flat preorder list; `level` gives
 * nesting — a child is exactly one level deeper than its parent).
 */
export interface OutlineEntry {
  title: string
  /** 0-based absolute page index in the assembled document. */
  pageIndex: number
  level: number
}
